services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/UnderSounds?allowPublicKeyRetrieval=true&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=8J]bWFPLG.:Qs2M2
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_REDIS_PASSWORD=-;((0ZRJ2alE/Q28
      - SPRING_APPLICATION_NAME=UnderSounds-Backend

    depends_on:
      - db
      - redis
    networks:
      - undersounds-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"
    networks:
      - undersounds-network

  db:
    image: mysql:8
    container_name: UnderSounds-DB
    environment:
      MYSQL_ROOT_PASSWORD: 8J]bWFPLG.:Qs2M2
      MYSQL_DATABASE: UnderSounds
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - undersounds-network

  redis:
    image: redis:7
    container_name: UnderSounds-Caching-DB
    command: ["redis-server", "--requirepass", "-;((0ZRJ2alE/Q28"]
    ports:
      - "6379:6379"
    networks:
      - undersounds-network

# Volúmenes persistentes para MySQL
volumes:
  db-data:

# Redes personalizadas para facilitar la comunicación entre contenedores
networks:
  undersounds-network:
    driver: bridge
